### ISSUE TITLE
Definir Requisitos

### ISSUE THREAD

**Issue by arthurfreire** [devfest-ufrn/livrei#1]
Definir requisitos do sistema e criar um documento de requisitos

**Comment by inhandui** [comment]
A partir das respostas do formulário nós podemos montar os requisitos do sistema abordando as dificuldades encontradas.

**Comment by inhandui** [comment]
- [x] bla.

**Comment by inhandui** [comment]
### Informações obtidas do primeiro formulário.
-Metade das pessoas entrevistadas nunca fez uma troca de produtos.
-Das pessoas que fizeram uma troca os produtos trocados foram: roupas, xbox, notebook, maquiagem, produtos de cabelo, celular e televisão.
-Para 85% das pessoas os produtos foram úteis. 
-Para 78% das pessoas a troca foi justa.
-Para 62% das pessoas foi difícil encontrar uma pessoa pra trocar.
-Para metade das pessoas não tiveram dificuldade em fazer uma troca e 30% tem dificuldade em confiar nas informações.

**Comment by inhandui** [comment]
Devido a dificuldade de montar um produto que atenta a uma diversidade muito grande de grupos de usuários, foi definido que vamos focar no nicho de troca de livros.

**Comment by inhandui** [comment]
- [ ] Cadastrar usuário.

- [ ] Autenticar usuário.

- [ ] Adicionar produtos.

- [ ] Procurar produtos.

- [ ] Visualizar produtos.
